version: '3.8'

networks:
  local:
    name: local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1

services:
  postgresql:
    platform: linux/amd64
    image: postgres:latest
    container_name: floor-plan-postgres-latest
    hostname: postgresql
    volumes:
      - ${DATA_PATH_HOST}/postgresql/data:/data
      - ./postgresql/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - local

  pgadmin:
    image: dpage/pgadmin4
    container_name: floor-plan-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - '${PGADMIN_PORT}:8001'
    depends_on:
      - postgresql
    networks:
      - local

  redis:
    platform: linux/amd64
    image: redis:${REDIS_VERSION}
    container_name: floor-plan-redis-${REDIS_VERSION}
    hostname: redis
    entrypoint: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/redis/data:/data
    ports:
      - '${REDIS_HOST_PORT}:6379'
    networks:
      - local
    tty: true
